docs/api/writing.md
Got confused as a newcomer to postgrest on how to update a single record. I feel the docs could benefit by having an example of updating that uses filtering. This is just proposed text.
=> Record Update documentation

docs/api/reading.md, docs/install/ecosystem.md, postgrest.dict
Clarifies situation raised in https://github.com/begriffs/postgrest/issues/685
=> Give an example of RPC

auth.rst
=> corrected url which calls jwt_test

admin.rst, auth.rst
https://github.com/begriffs/postgrest/pull/772
=> Documentation updates for postgrest pull #772

admin.rst
I've added a small comment where I think it will be useful. Hope this covers it :)
=> Document connect strings for older versions of libpq (#11)

auth.rst
Code blocks with code:postgres are not highlighted (see site navigation), not works. Replaced by code:sql that works "fine"
=> replace code:postgres by code:sql

intro.rst
Fixes https://github.com/begriffs/postgrest/issues/825
=> More extensions, example apps, client side libs

api.rst
Simple fix for https://github.com/begriffs/postgrest/issues/840
=> Fix duplicate wording

api.rst
Pull request for fix https://github.com/begriffs/postgrest/issues/839, props to @vog for for the updated PostgreSql index.
=> Fix Bad SQL coding practices in "Computed Columns" example

api.rst
It's gonna take me a while to complete WHERE support, for the moment I thought of adding this example as it was requested in a comment on gitter.
=> Add example for complex boolean logic

intro.rst
If you'd be so kind :)
Thank you
=> subzero domain change

install.rst
=> switch tar command for xz instead of gzip

admin.rst
of postgrest: ParseError "postgrest.config" "endOfInput"
=> Single quotes give an error

api.rst
I did something silly, forked again and created a different PR. This should be cleaner and includes all changes proposed in the last PR.
=> Updated docs for complex logic API capability

api.rst
=> Range operators and deprecation of symbol operators

install.rst
For begriffs/postgrest#919 and begriffs/postgrest#975.
=> Update JWT configuration section for JWK and aud

api.rst
Documents the changes from https://github.com/begriffs/postgrest/pull/885
=> Explain how sql comments appear in the openapi output

install.rst
Help ensure other Windows users don't run into the problem in https://github.com/begriffs/postgrest/issues/900
=> Add note that windows people need postgres on path

api.rst, index.rst, postgrest.dict, tutorials/tut1.rst
This PR updates the docs to be ready for a public 4.4 version.
The topics changed or added are each in a separate commit.
Please advise if I overlooked anything.
=> Changes in 4.4 release

admin.rst
It's a pain to do schema reloading manually and people forget to do it.
I have tested that these instructions work. My only question is whether we should include a more prominent link to this section because we get a *lot* of questions stemming from a stale schema cache.
=> Schema auto-reload instructions

install.rst
=> Update docker-compose example to version 3

install.rst
anon should not be the default db user
=> update PGRST_DB_ANON_ROLE in docker-compose

api.rst, install.rst
Work in progress, I'll release v0.5.0.0 docs when this is done.
=> Add new features from v0.5.0.0

install.rst
Added an additional docker-compose.yml with swagger gui as own container. updated docker-compose.yml do version 3
=> Add swagger GUI, docker compose v1 -> v3

auth.rst, install.rst
=> Clarify config and auth sections on JWKS.

api.rst, index.rst, install.rst, release_notes.rst, tutorials/tut0.rst, tutorials/tut1.rst
Work in progress. Looking to clear a good amount of issues.
=> Docs for v5.2.0

api.rst
add a NOTE, so lazy dev do not hit the wall.
=> update doc based on postgrest/issues/1253

auth.rst
Correct url https://github.com/michelp/pgjwt/blob/master/pgjwt--0.1.0.sql
=> SQL inside pgjwt

index.rst
we've been using PostgREST in internal production
infrastructure at Datrium for a few years now.
so, we're giving thanks in the form of a testimonial,
and providing a link to a python-based postgrest client
we developed and use.
=> add Datrium client library and testimonial

api.rst
Related to https://github.com/PostgREST/postgrest/pull/1385.
=> Add params=multiple-objects to api reference

api.rst
The names changed according to https://github.com/PostgREST/postgrest/issues/1378#issuecomment-531506803
=> Replace estimated with planned

api.rst, releases/upcoming.rst
Related to the changes in https://github.com/PostgREST/postgrest/pull/1391.
=> Add references for embedding on stored procedures and mutations

api.rst
_         -> HT.status400
When I have got  23514 error code from Postgres, I got 400 status code not 500.
=> fix api.rst other status from 500 to 400

api.rst
Wonderful project. And the documentation is very detailed too. Thank you.
=> Typo (repeated word)

ecosystem.rst, index.rst
=> Add Community Tutorials section

index.rst
See discussion here: https://github.com/PostgREST/postgrest-docs/commit/3dde972d31519d3afc319015bce1dc0f73adeb8e#commitcomment-35312841
I really appreciate the link. PostgREST is one of the best opensource projects I've ever used
=> Removing fragment from URL

ecosystem.rst
Adding https://gis-ops.com/postgrest-postgis-api-tutorial-in-5-minutes/.
=> Add GISOPS community tutorial

ecosystem.rst
=> Add postgrest-sessions-example to Example Apps

ecosystem.rst
Fyi I'm the main contributor for this library ^^.
=> Add postgrester client library

ecosystem.rst
Hey Steve, just a small addition with one of our client libraries. It doesn't like like there is any ordering on the list so I claimed pole-position. Happy to reshuffle it though.
Once again, thanks for everything!
=> Adds new JS client library to /ecosystem

api.rst, configuration.rst, releases/upcoming.rst
For the upcoming version. Work in progress..
=> New features for the 7.0 release

index.rst
Found this out in [Ask HN: Who is hiring? (February 2020)](https://news.ycombinator.com/item?id=22245971). Also confirmed by them through email.
=> Add sompani to production list

auth.rst
Or the function login will show error.
=> Add type basic_auth.jwt_token.

ecosystem.rst
Added the link to tutorial to configure and integrate Auth0 to PostgREST
=> Added the link to tutorial to configure and integrate Auth0 to PostgREST

ecosystem.rst
Hey! We developed a Vue.js library, happy to be part of this. Thank you for postgREST!
=> Add new JS (Vue) client to /ecosystem

api.rst
Related to https://github.com/PostgREST/postgrest/pull/1541
Preview: https://postgrest.org/en/preview/api.html#setting-response-status-code
=> reference: Add response.status GUC

ecosystem.rst
Hey there, I made a little thingy 🦀. Just adding another one to the list!
=> Add supabase/postgrest-rs client library

schema_structure.rst
As discussed in the #334 issue.
=> Fix #334: Alter default privileges

ecosystem.rst
Updated the link to the blog post for PostgREST + Auth0 tutorial
=> Updated the link to the blog post for PostgREST + Auth0 tutorial

ecosystem.rst
=> Add postgrest-vercel and postgrest-node to community tutorials

api.rst, releases/upcoming.rst
docs for https://github.com/PostgREST/postgrest/pull/1603
=> Calling variadic functions

index.rst
Changes:
- add netwo
- add how to guide :)
- fix my name :')
=> Add how to guide, netwo and fix my name ^^

api.rst
Following up on https://github.com/PostgREST/postgrest/pull/1625#issuecomment-728357780.
What do you think @steve-chavez?
=> Add note about embedding of view-chains and the interaction with `db-extra-search-path`

install.rst
=> Add chocolatey installation method

install.rst
=> Minor grammar fix

tutorials/tut1.rst
Fixed the numbering for the steps in the second tutorial page, i'm sorry if the double Step 4 was intended
=> Fixed the numbering for the steps

ecosystem.rst, index.rst
- Adds all client libraries from Supabase
- "In production" section: we use PostgREST internally and as part of every customer project
=> Add client libraries

ecosystem.rst
=> Fix broken link for 5min tutorial

tutorials/tut0.rst
Adding a note to help people who are hitting this error `{"hint":null,"details":null,"code":"42P01","message":"relation \"api.todos\" does not exist"}`
https://github.com/PostgREST/postgrest/issues/1009
=> Adding a hint to Hello World

ecosystem.rst
Add Postgrest-ex to list of client libraries. Thanks for creating this project :)
=> Add Elixir  Client library

ecosystem.rst
=> Add Supabase-go Library Ecosystem

api.rst, postgrest.dict, releases/upcoming.rst
=> Add an option section to API reference page

configuration.rst, releases/upcoming.rst
Added documentation on the `log-level` config option.
=> Add log-level config option

api.rst, releases/upcoming.rst
Added documentation according to https://github.com/PostgREST/postgrest/pull/1813.
=> Add explicit headers-only POST request using Prefer header

configuration.rst, releases/upcoming.rst
Added documentation according to #409 (only reloading with SIGUSR2 is included).
=> Add config reloading with NOTIFY and SIGUSR2

api.rst, releases/upcoming.rst
=> Add changelog for embedding views recursively

api.rst, index.rst, releases/upcoming.rst
=> Add partitioned tables in the schema cache

requirements.txt
Apparently, the latest fix consisting in changing the docutils to v0.17.1 broke some styles, I'll test changing the versions to older ones to see if it fixes the issue.
=> Fix broken styles

install.rst, postgrest.dict
Shows the installation methods in a more organized way.
=> Use tabs to show different installation methods

api.rst
Adds an example to upload binary files.
=> Add example to rpc unnamed single bytea parameter

api.rst, releases/upcoming.rst
Related to https://github.com/PostgREST/postgrest/pull/2027/files
=> Allow unknown for is operator

api.rst, releases/upcoming.rst
Related to https://github.com/PostgREST/postgrest/pull/2022
=> Remove partitions from the schema cache

api.rst, configuration.rst, releases/upcoming.rst
Related to https://github.com/PostgREST/postgrest/pull/2034.
=> Remove the db-embed-default-join config

api.rst, auth.rst, install.rst
Related: https://github.com/PostgREST/postgrest/pull/2038
=> Drop support for PG 9.5.

api.rst, auth.rst, tutorials/tut1.rst
=> Fix GUC names using the old syntax

admin.rst
Related to https://github.com/PostgREST/postgrest/pull/2115
Will wait with merging this until I have #483 done - would like to push that other MR to the stable branch, too.
=> add user to logging example

schema_cache.rst
Resolves https://github.com/PostgREST/postgrest-docs/issues/445.
=> Add finer-grained event trigger

admin.rst, auth.rst, configuration.rst, releases/v8.0.0.rst, tutorials/tut0.rst
Related to https://github.com/PostgREST/postgrest/pull/2112
=> Run PostgREST with zero config. 

docs/install.rst
=> Improve docker installation examples

docs/api.rst, livereload_docs.py
Related to https://github.com/PostgREST/postgrest/pull/2145
=> Accessing array items and fields of composite types

docs/install.rst
replacing postgrest 2 with postgrest -e
=> updated the example config switch

docs/api.rst
Adds examples to the information added in #501.
=> Add example for array and composite type columns

docs/auth.rst
Fixing https://github.com/PostgREST/postgrest-docs/issues/469
=> Backward compatible (server versions < 14) code example for getting claims in SQL

docs/admin.rst, docs/configuration.rst
Related to:
- https://github.com/PostgREST/postgrest/pull/2109
- https://github.com/PostgREST/postgrest/pull/2092
- https://github.com/PostgREST/postgrest/pull/2107
=> Add documentation on the minimal health check

docs/api.rst
Related to https://github.com/PostgREST/postgrest/pull/2152
=> Add hint on how to prevent exposing computed columns as RPCs

docs/admin.rst, docs/configuration.rst
Related to https://github.com/PostgREST/postgrest/pull/2182#issuecomment-1063971738
=> Add information on specifying hostnames for multiple instances

docs/how-tos/working-with-postgresql-data-types.rst, postgrest.dict
Closes https://github.com/PostgREST/postgrest-docs/issues/273
=> Add how to on PostGIS and hstore data types

docs/api.rst, postgrest.dict
=> feat(api): add match/imatch operators for regular expression support

docs/api.rst, docs/ecosystem.rst, docs/errors.rst, docs/install.rst, docs/releases/v8.0.0.rst, docs/schema_cache.rst
For https://github.com/PostgREST/postgrest/pull/2195
=> Docs for limited updates/deletions

docs/api.rst, docs/errors.rst, postgrest.dict
Related to [#2270](https://github.com/PostgREST/postgrest/pull/2270).
=> Reorganize group errors

docs/api.rst
=> Add documentation on embedding views containing joins

docs/api.rst
Related to https://github.com/PostgREST/postgrest-docs/pull/536#discussion_r876534095
=> Fix main explanation on views with joins

docs/how-tos/working-with-postgresql-data-types.rst
Adds examples for Array types in the "How-to work with PostgreSQL types" page.
=> Add how to work with array columns

docs/how-tos/working-with-postgresql-data-types.rst
Adds more special timestamp values to the example.
=> Add more special timestamp values

docs/index.rst, docs/releases/latest.rst, docs/releases/v9.0.1.rst, postgrest.dict
Adds the `v9.0.1` changelog and updates the `latest` one.
=> Add 9.0.1 changelog

docs/api.rst, docs/releases/latest.rst, postgrest.dict
Docs for https://github.com/PostgREST/postgrest/pull/2311
=> Add bulk update

docs/errors.rst
=> clarify errors

docs/how-tos/working-with-postgresql-data-types.rst
The bodies of the responses are in JSON array format but they should be in JSON object format. If the user has no control over Headers to get a single response, then it's better to use a `function` than a `view`. Related to https://github.com/PostgREST/postgrest/discussions/2338 and https://github.com/PostgREST/postgrest/discussions/2339.
=> Modify GeoJSON examples from views to functions

docs/how-tos/create-soap-endpoint.rst, docs/index.rst
=> HOW-TO for SOAP

docs/api.rst
Update for https://github.com/PostgREST/postgrest/pull/2262
=> new m2m relationship detection

docs/install.rst
Heroku installation docs aligned with the postgrest-heroku buildpack README.md
=> Heroku installation docs aligned with PR #40

docs/api.rst, docs/auth.rst, docs/ecosystem.rst, docs/tutorials/tut0.rst, postgrest.dict
=> Fixes tutorial, auth and broken links

docs/configuration.rst, docs/releases/v6.0.2.rst
Related to https://github.com/PostgREST/postgrest/pull/2449
=> Add db-pool-acquisition-timeout configuration parameter

docs/api.rst
=> Fix info on updates without filters

docs/api.rst
=> Add caveats when working with computed relationships

LICENSE, docs/api.rst, docs/auth.rst, docs/configuration.rst, docs/errors.rst, docs/how-tos/sql-user-management-using-postgres-users-and-passwords.rst, docs/index.rst, docs/install.rst, docs/releases/v10.2.0.rst, docs/releases/v6.0.2.rst, docs/schema_cache.rst, postgrest.dict
Picks/modifies commits and adds changes for version 10.2.0.
**Note:** Release after https://github.com/PostgREST/postgrest-docs/pull/604 is merged and cherry-picked.
=> Documentation for v10.2.0

docs/configuration.rst, docs/index.rst, docs/install.rst, docs/releases/v10.2.0.rst
Picks the commits done for v10.2
=> Add  v10.2 relase documentation

docs/admin.rst, docs/configuration.rst, docs/connection_pool.rst, docs/errors.rst, docs/index.rst, docs/install.rst
- Document connection pool features.
- Moves some sections from the Admin page to the new connection pool page.
- Adds some recommendations to avoid the Acquisition Timeout.
Considered the https://hemingwayapp.com/ score for all paragraphs.
=> connection pool reference

docs/ecosystem.rst, docs/integrations/greenplum.rst, docs/integrations/jwt_gen.rst, postgrest.dict
* Move Nginx and systemd to integration
* Move External JWT Generatio to integration
* greenplum short notice
---
Closes https://github.com/PostgREST/postgrest-docs/issues/467
=> add integrations

docs/index.rst, docs/references/api/stored_procedures.rst, docs/releases/v11.0.1.rst, postgrest.dict
Related to https://github.com/PostgREST/postgrest/issues/1652. Make it clear we inline functions.
=> Add function inlining

docs/references/configuration.rst, docs/releases/unreleased.rst, postgrest.dict
Related to https://github.com/PostgREST/postgrest/pull/2803
=> Add pre-config function

docs/references/api/stored_procedures.rst, docs/references/errors.rst, docs/references/transactions.rst
Closes https://github.com/PostgREST/postgrest-docs/issues/633
=> references: move raise error to errors page

docs/ecosystem.rst, postgrest.dict
Removes old and unmaintained links in the ecosystem that may not be up to date with the latest PostgREST versions.
=> Remove old or unmaintained links from ecosystem

docs/references/connection_pool.rst
=> Update connection_pool.rst typo

docs/references/admin.rst
Related to https://github.com/PostgREST/postgrest/issues/2647 and https://github.com/PostgREST/postgrest/issues/2848
=> add version querying

docs/ecosystem.rst, docs/references/admin.rst, docs/references/configuration.rst, docs/references/connection_pool.rst, postgrest.dict
Closes https://github.com/PostgREST/postgrest-docs/issues/662
=> dry config and make it responsive

docs/references/errors.rst
Documentation for feature [allow full response control](https://github.com/PostgREST/postgrest/pull/2911).
=> allow add-headers-with-raise

docs/references/api.rst, docs/references/api/preferences.rst, docs/references/errors.rst, postgrest.dict
Documentation for `Prefer: handling=strict/lenient`.
=> add documentation for handling preference

docs/references/auth.rst, docs/references/configuration.rst
Documentation for JWT caching feature.
=> add documentation for JWT caching

docs/how-tos/providing-html-content-using-htmx.rst, docs/references/api/media_type_handlers.rst, postgrest.dict
Related to https://github.com/PostgREST/postgrest/pull/2825
=> doc: media type handlers

docs/index.rst
Related to https://github.com/PostgREST/postgrest/pull/3042
=> Remove former sponsors

docs/how-tos/working-with-postgresql-data-types.rst, docs/references/api/preferences.rst
Documentation for timezone preference.
=> add documentation for timezone preference

docs/references/admin.rst, docs/references/configuration.rst
depends on https://github.com/PostgREST/postgrest/issues/3062
=> introducing server-timing-header config parameter

docs/references/api.rst, docs/references/configuration.rst, docs/references/transactions.rst, postgrest.dict
Related to https://github.com/PostgREST/postgrest/pull/3032
=> Remove db-use-legacy-gucs

docs/references/admin.rst, docs/references/api/url_grammar.rst, docs/references/auth.rst, postgrest.dict
=> fix server-timing header section

docs/how-tos/providing-images-for-img.rst, docs/index.rst, docs/references/health_check.rst, docs/references/observability.rst, postgrest.dict
=> Separate Admin into Observability and Health Check

docs/references/api/media_type_handlers.rst
Otherwise it cannot be reused. Related to https://github.com/PostgREST/postgrest/issues/3089#issuecomment-1840842309
=> fix: any media type should be bytea

docs/references/configuration.rst
Related to https://github.com/PostgREST/postgrest/pull/3102
=> Add missing in-db configuration for jwt-cache-max-lifetime

docs/how-tos/providing-html-content-using-htmx.rst
Adds experimental warning and fix html sanitization.
=> Add warning and fix to htmx how-to

docs/references/api/preferences.rst
Add documentation for `max-affected` preference.
=> add documentation for max-affected preference

docs/references/api/media_type_handlers.rst
Otherwise users think they're required steps. See the opening comment on https://github.com/PostgREST/postgrest/issues/3124.
=> docs: testing of media handlers as a note

docs/explanations/nginx.rst, docs/how-tos/sql-user-management-using-postgres-users-and-passwords.rst, docs/how-tos/sql-user-management.rst, docs/how-tos/working-with-postgresql-data-types.rst, docs/integrations/pg-safeupdate.rst, docs/references/api/aggregate_functions.rst, docs/references/api/computed_fields.rst, docs/references/api/cors.rst, docs/references/api/domain_representations.rst, docs/references/api/openapi.rst, docs/references/api/options.rst, docs/references/api/pagination_count.rst, docs/references/api/preferences.rst, docs/references/api/resource_embedding.rst, docs/references/api/resource_representation.rst, docs/references/api/schemas.rst, docs/references/api/stored_procedures.rst, docs/references/api/tables_views.rst, docs/references/api/url_grammar.rst, docs/references/auth.rst, docs/references/health_check.rst, docs/references/observability.rst, docs/references/transactions.rst
=> Remove HTTP Snippets

docs/references/api/tables_views.rst
=> Use `-g` to prevent globbing in some curl examples
