mkdocs.yml

@NikolayS suggested that the main use case on the docs is to go try the program rather than contribute to docs, hence the changed link. Seem good?

Github link to main project rather than docs repo in the docs

---

api.rst

- mention that it's not only about reading data (now `/rpc/...` are in Reading section of http://postgrest.com/api/reading/, maybe to move it to separate section?)
- list of some procedural languages supported by Postgres
- how to deal with permissions, briefly

more about stored procedures

---

install.rst

Builds of 0.4 repeatedly fail on the first dependency when building on a Digital Ocean Ubuntu 16.04 box with 1GB of ram. Adding 2GB of swap fixed the issue.

Suggest swap file on systems with under 1GB of ram

---

admin.rst
api.rst

The current documentation reflects the headers that must be set for singular object responses in postgrest v0.3. This change updates the documentation to reflect the way it works in v0.4, as noted by @begriffs in https://github.com/begriffs/postgrest/issues/776#issuecomment-275026837
I hope I got it right :)

Fix the plurality header docs for v0.4

---

index.rst

The index page has `<no-title> -- PostgREST 0.4.0.0 Documentation` for HTML title, using the `title` directive, we can force it to something nicer.
I'm not sure if this fixes it at the top of the page.
http://docutils.sourceforge.net/docs/ref/rst/directives.html#metadata-document-title
http://www.sphinx-doc.org/en/stable/rest.html#directives

Override document title for index.rst

---

api.rst

Added the docs for https://github.com/begriffs/postgrest/pull/802. Also I changed the order of the OpenAPI section, I felt it out of place somehow and thought it was better placed at the end of the page.

Add section for binary output

---

auth.rst

From the [docs](https://auth0.com/docs/metadata):
> An authenticated user can modify data in their profile's `user_metadata`, but not in their `app_metadata`.
Seems role-type information should be stored in `app_metadata`. For s'curity

Auth0 -- app metadata instead of user metadata

---

auth.rst

Just some minor fixes to the example scripts to make them functional.  I'm not sure if the "jwt" schema was intentional; if so, the purpose should probably be stated in the docs.

auth.rst: minor fixes to example scripts

---

intro.rst

The first example on the doc site was redirecting to a page within the read the docs site due to the link target and text being swapped.

intro.rst: Correct first example app link

---

auth.rst

Auth0 is pushing users to a new authentication process.
To this end, they've made default a setting that postgrest cannot yet accommodate. See details in begriffs/postgrest#906.
Users can continue integrating with Auth0 if they
- Toggle off OIDC-conformant authentiction, which, as of yesterday, is default for new clients
- Remove `audience` configuration from the call to auth0's authentication endpoint
This configuration has been added to the example integrations
To see current broken setup:
1. Create rule
```
function (user, context, callback) {
user.role = 'basic_user'
callback(null, user, context);
}
```
2. Create new Auth0 client in dashboard
3. Download the sample js app; `npm install`; `serve 8080`
4. In `app.js` change in `webAuth` config:
- Change `scope: 'openid'` to `scope: …

Add notice about reverting OIDC default

---

tutorials/tut0.rst

Update tut0.rst with improved instructions for windows installs to fix begriffs/postgrest#1040

Update tut0.rst to fix begriffs/postgrest#1040

---

tutorials/tut0.rst

Replace `to to ` with `to the `.  Alternative was remove the second `to `.  Thoughts?

Fix typo - 'Connect to to SQL console'

---

api.rst

This is a pretty major caveat for views which ought to be noted (see #172).
I did not  note the read-only workaround (create a stored procedure with the "SECURITY INVOKER" option).
Relevant chatter about this:
- https://stackoverflow.com/a/33863371
- https://www.postgresql.org/message-id/flat/CABFpK629xHR-jbgO0tiprMr9aZLiofMkQ3E7QxqHFRVFNcqnSQ%40mail.gmail.com

Note Postgres' (current) RLS limitations for views

---

api.rst

This problem has already been discussed in https://github.com/PostgREST/postgrest/issues/1118. I think the documentation would benefit from that knowledge, as it's a very common scenario.

clarify the usage of upsert when the table uses a surrogate key

---

api.rst

Closes #202. 
Tests were also added in another [PR](https://github.com/PostgREST/postgrest/pull/1337).

Add missing doc for the ov operator in array types

---

api.rst

If [#1339](https://github.com/PostgREST/postgrest/pull/1339) is accepted, this PR adds the proper documentation.

Add websearch_to_tsquery doc

---

install.rst

On macOS, it is also necessary to add the IP address in the listen_address within pg_hba.conf (tested with PostgreSQL 11.3 and postgREST v6.0.0)

Updated Docker section

---

admin.rst
index.rst
install.rst
tutorials/tut1.rst

Running `sphinx-build` (via the `make` targets at least) generates some minor warnings.
The PR fixes them, one per commit. Each warning is mentioned in the commit message.
Note: I couldn't find any contributing guideline, so indications are welcome.

Fix miscellaneous Sphinx warnings

---

install.rst

When using swagger-ui with postgrest in docker compose, the host reported by the OpenAPI spec will default to `0.0.0.0` since this is the host on the container network. Since this is what swagger-ui uses for all but the first request, (to fetch the spec). This means that whenever `0.0.0.0` doesn't resolve to localhost on the host machine swagger-ui won't work. Setting `PGRST_SERVER_PROXY_URI` (server-proxy-uri) means a sensible default is set to make it more plug and play.

Add server proxy uri env var for smoother swagger-ui  use with docker-compose

---

how-tos/casting-type-to-custom-json.rst
how-tos/embedding-table-from-another-schema.rst
tutorials/tut0.rst
tutorials/tut1.rst

Doing `tutorials` and `how-tos` take considerable time and effort. I want to credit authors as a way to encourage more contributions.
The link to authors profiles can be any of their choosing(github, website, etc).
Since how-tos can be so diverse, I'm thinking we could even allow blog posts/articles from external websites and link them to our [how-tos section](https://postgrest.org/en/preview/index.html#how-to-guides).
Author preview samples:
- https://postgrest.org/en/preview/tutorials/tut0.html
- https://postgrest.org/en/preview/how-tos/casting-type-to-custom-json.html
Ideally this would look better but for now I just left it with readthedocs default css.
(cc @begriffs)

Credit tutorials and how-tos authors

---

admin.rst

Related to https://github.com/PostgREST/postgrest/issues/1399#issuecomment-554906927.
I'm not sure exactly why this happens since I haven't reproduced the issue. However, our initial nginx recommendation should be simple and adding optimizations could be left to a more advanced section.

Remove keepalive nginx recommendation

---

admin.rst

The command help shows 
```
pg_listen db-url channel /path/to/program [args]
```
Putting the command in quotes actually caused 
```
Can't run killall -SIGUSR1 postgrest: No such file or directory
```
error since pg_listen interprets the entire quoted command as the executable.

Fixed the pg_listen syntax

---

how-tos/providing-images-for-img.rst
index.rst

I tried to setup an endpoint for providing binary data for <img> tags. This is what I found out.
I need some help with the following point.
- Return 404 when the requested id is not present in table.
If we could trigger raw output via a config parameter from within the procedure, we could provide a generic file endpoint. Setting `raw-media-types= */*` is probably not a good idea. Is this worth a
feature request?
Addresses #233.

Tutorial: Providing images for <img>

---

auth.rst

I struggled for a while to make it work, but in the end found that https://www.postgresql.org/docs/9.5/sql-createpolicy.html says you have to run `ALTER TABLE ... ENABLE ROW LEVEL SECURITY;` and that appears to have fixed the issue.
Also I'm not sure the documentation about `current_setting` would be good practice. If you do not pass the `true` argument to return NULL if the setting is missing the error will be much more obvious (and this is also what is done in the [linked tutorial](https://www.2ndquadrant.com/en/blog/application-users-vs-row-level-security/)).
In my opinion `current_setting('request.jwt.claim.email')` would be better, but let me know what you think because I'm not exactly an expert.

Fix the 'Roles for Each Web User' example

---

ecosystem.rst

Old playlist is gone - linked to first video in series instead

Fix link to DigitalOcean PostgREST Contact List video

---

install.rst

Documentation on the alternative ways to run tests locally that would be added with https://github.com/PostgREST/postgrest/pull/1476 and https://github.com/PostgREST/postgrest/pull/1480.

Documentation on how to run the test suite locally

---

ecosystem.rst

As per https://github.com/andytango/redux-postgrest/issues/7

add redux-postgrest to client-side libraries

---

admin.rst
ecosystem.rst

Change broken Bitbucket links for pg-safeupdate to GitHub.
For issue #336

Fix links to pg-safeupdate 

---

install.rst

This PR if a follow up to 
- [PostgRest#1445](https://github.com/PostgREST/postgrest/issues/1445): Chocolatey or scoop package for PostgREST
- [ScoopMain#1250](https://github.com/ScoopInstaller/Main/pull/1250): postgrest: Add version 7.0.1

Add Windows installation using Scoop to install page

---

tutorials/tut0.rst

With the current order, the tar command thinks the name of the archive is J.

Fix order of options in tar command

---

development.rst

Without zlib1g-dev the build process fails.

Missing library dependency

---

_static/css/custom.css
index.rst

While this "works", I'm not 100% convinced, yet. We tend to not have as much text and those single sentences stretched out across the whole screen are not really better to read. Do we need to do more styling here?
I tried just copying in all the linux-docs css overrides (as this style as mentioned in #351), but I'm not sure of that either.
What do you think @steve-chavez?

make docs full-width, resolves #351

---

install.rst

Also removed a deprecated `links` setting from the docker-compose, since that's not needed any more
Resolves #379

Fix outdated environment variable for docker compose

---

README.md

Removing a couple of things where I feel we don't need them anymore. Split up in 3 commits, because some of them might be more controversial then others ;)
1. Makefile and Pipfile: The Makefile does not seem to be used at all. If anything from that is needed, we should add nix-tools instead. The Pipfile would only make sense when not using nix, but I don't it's worth to maintain it. I tried it once, but using it failed because I have python3.8 and not 3.6 on the system. I then gave up and used nix - worked instantly. Regarding the Makefile I also checked the build-log for readthedocs, it seems to run the needed commands itself without the makefile. Should be safe to remove.
2. The chinese translation is heavily outdated - I don't think there is any value in pointing to it anymore. There's …

For discussion: Remove obsolete stuff

---

install.rst

I have never used Heroku. Is this "Master" referencing the default github branch? Then it should be changed as suggested.

change Master to Main in heroku deploy steps

---

api.rst
configuration.rst
releases/upcoming.rst

Added documentation for the `openapi-mode` configuration option according to https://github.com/PostgREST/postgrest/pull/1881.
Closes #293.

Add openapi-mode configuration option

---

api.rst
releases/upcoming.rst
schema_cache.rst

* Documents the error message for not found RPC on a stale schema
* Documents that overloaded RPC with the same argument names but different types are not supported

Add documentation on error messages for RPC on a stale schema

---

configuration.rst
postgrest.dict
releases/upcoming.rst

Added documentation on `db-tx-end` config option according to https://github.com/PostgREST/postgrest/pull/1659 and https://github.com/PostgREST/postgrest/pull/1668.

Add db-tx-end config option

---

admin.rst
configuration.rst
postgrest.dict
releases/upcoming.rst

Added documentation on the `db-prepared-statements` config option according to: https://github.com/PostgREST/postgrest/pull/1633 and https://github.com/PostgREST/postgrest/pull/1888.

Add db-prepared-statements config option

---

configuration.rst

I had a `docker-compose.yml` with some environment variables in it and I couldn't really find any mention of them when searching Google for `PGRST_DB_URI` (other than the example). I think this small addition will make that a bit more discoverable.

Mention environment variables in the configuration section

---

ecosystem.rst
releases/upcoming.rst

Now that Nightlies are deprecated, the latest builds can be downloaded from the resulting Artifacts from CI runs.

Add link and explanation to download the latest unreleased builds

---

admin.rst
configuration.rst
releases/v8.0.0.rst

Specify that the connection poolers are external and not from PostgREST itself.

Specify external connection pooler

---

api.rst

The correct setting name is `ignore-privileges`, with dash in between the words.
Docs:
https://postgrest.org/en/v8.0/configuration.html?highlight=openapi%203#openapi-mode

Typo in api.rst

---

api.rst
releases/upcoming.rst

Documentation for https://github.com/PostgREST/postgrest/pull/1927
Replaces https://github.com/PostgREST/postgrest-docs/pull/431

Allow rpc POST with single unnamed parameter

---

api.rst
postgrest.dict
releases/upcoming.rst

The `and` and `or` operators are somewhat "hidden" in the Horizontal Filtering section. This PR groups them in a subheading and adds them to the operator list.

Add the logical operators section in horizontal filtering

---

configuration.rst

I saw this typo when I was reviewing the configuration documentation

Add missing = in log-level docs

---

releases/v5.2.0.rst

This is making the linkcheck fail, currently. The link is dead, because we removed the old docs. Should be fine without.

remove dead link to v5 docs

---

admin.rst
api.rst
auth.rst
configuration.rst
how-tos/embedding-table-from-another-schema.rst
postgrest.dict
releases/v7.0.0.rst
tutorials/tut0.rst
tutorials/tut1.rst

This is kind of a rework of the configuration page, including:
- Adding the missing `db-root-spec` config parameter
- Renaming the config parameters according to https://github.com/PostgREST/postgrest/pull/1679
- Sorting all config parameters alphabetically
- Adding names for environment variables and database settings for each parameter
- Re-organizing the whole page, so that the list of parameters is last (so that the environment and database sections come before the list, which already mentions the names for those settings)

Update configuration page

---

api.rst

[I ran into a gotcha](https://github.com/PostgREST/postgrest/issues/2138). Improving docs so that others can avoid this.
This is my first PR in this project, and I haven't tested the generated docs. Feel free to discard if it's not appropriate or not done correctly.

Improving docs for setting response headers like content-type

---

how-tos/providing-images-for-img.rst
releases/v7.0.0.rst
releases/v8.0.0.rst
releases/v9.0.0.rst
tutorials/tut0.rst

As noticed in #492 some references are pointing to the first section of a document, when they should instead point to the full document. This doesn't make any difference to the user afaik, but is more about consistency.

Fix references to full documents instead of first section

---

docs/admin.rst
postgrest.dict

Related to https://github.com/PostgREST/postgrest/pull/2158.
Timeouts can be better explained when the `/metrics` endpoint is available, so I've just scoped this PR to file descriptors.

Add admin section on file descriptors

---

requirements.txt

Fix bullet points and separations not showing correctly for unordered lists. Pinned package versions following this PR as reference https://github.com/datalad/datalad/pull/6346

Fix unordered list styles

---

docs/ecosystem.rst

Fixed incorrect link for the swift library in Client-Side Libraries section. It now links properly to: https://github.com/supabase-community/postgrest-swift

Update ecosystem.rst to fix incorrect link in Client-Side Libraries section

---

docs/api.rst
docs/configuration.rst
docs/errors.rst
docs/releases/v6.0.2.rst

cf.
- https://github.com/PostgREST/postgrest/pull/2202
- https://github.com/PostgREST/postgrest/pull/2268
- I have not adapted https://postgrest.org/en/latest/api.html#response-format because
- `text/plain` isn't listed there either - a mistake?
- As far as I understand it should be made clear that `application/octet-stream`, `text/plain`, `text/xml` only work under the conditions mentioned in https://postgrest.org/en/latest/api.html#binary-output ?
- Now we have 3 paragraphs https://postgrest.org/en/latest/api.html#binary-output, https://postgrest.org/en/latest/api.html#plain-text-output, https://postgrest.org/en/latest/api.html#xml-output .
- Both plain-text-output and xml-output just talk about "columns" not mentioning RPC return values
- Maybe we should merge all three paragraphs, …

Allow returning XML

---

docs/configuration.rst

Using the symbol `$` fails when using it in values of the configuration file (not when using environment variables). Needs `$$` in order to interpret it as a single `$`. This is due to these lines in the configuration parser: https://github.com/robx/configurator-pg/blob/master/src/Data/Configurator/Syntax.hs#L137-L138.

Add disclaimer on $ usage in jwt-secret values

---

docs/how-tos/providing-images-for-img.rst
docs/how-tos/working-with-postgresql-data-types.rst
docs/index.rst
postgrest.dict

Closes #539 and adds info mentioned in https://github.com/PostgREST/postgrest-docs/issues/539#issuecomment-1136213676

Add bytea to working with types and improve img example

---

docs/api.rst

documentation concerning https://github.com/PostgREST/postgrest/pull/2300

RPC POST for function w/single unnamed XML param, postgrest-PR #2300

---

docs/index.rst
docs/releases/v9.0.1.rst
postgrest.dict

Related to the [v9.0.1 release](https://github.com/PostgREST/postgrest/releases/tag/v9.0.1).

Bump to v9.0.1

---

docs/api.rst

Looks like a copy-paste error - the `films.id` column should be associated with the `premieres.film_id` column.

Fix example code in computed relationships

---

docs/how-tos/working-with-postgresql-data-types.rst

Removes some unnecessary connectors from the paragraphs and rewords some sentences in favor of more fluidity.

Shorten explanations for the working with types section

---

docs/api.rst
postgrest.dict

Specify that preflight requests are supported, returning the max-age required for caching.

Add information on preflight requests

---

docs/auth.rst
docs/how-tos/sql-user-management-using-postgres-users-and-passwords.rst
docs/index.rst
postgrest.dict

As discussed in #562, here is a suggestion for a how-to on "SQL User Management using postgres’ users and passwords", without a dedicated users table and dedicated passwords.
It all boils down to implementing SCRAM-SHA-256 password verification in PL/pgSQL and verifying against `pg_authid.rolpassword` .
Debatable choices are:
* There are quite many references to the main docs article, leading to wordings as "As described in ...", "Analogous to ..."
* The extensive testing section - but I think this can help understanding what happens; and it even is a small security test.
* SQL keywords upcased for better readability?
* The whole thing: Are a PBKDF2 function taken from stackoverflow plus some self-engineered function `check_user_pass` secure enough?
Please review; thank you!

how-to: SQL User Management using postgres’ users and passwords

---

docs/auth.rst
docs/configuration.rst
docs/ecosystem.rst

> Perhaps we can recommend an additional measure: a db-pre-request that only enables the plan media type from certain IPs, otherwise rejects it.
Discussed on https://github.com/PostgREST/postgrest/pull/2368#issuecomment-1189816556

Add db-plan-enabled recommendation

---

docs/errors.rst
postgrest.dict

Adds HTTP status codes to the PGRST errors. Also removes deprecated errors and adds missing ones.

Add HTTP status codes to PGRST errors

---

docs/auth.rst
docs/configuration.rst
docs/db_authz.rst
docs/ecosystem.rst
docs/how-tos/sql-user-management-using-postgres-users-and-passwords.rst
docs/how-tos/sql-user-management.rst
docs/index.rst
docs/releases/v10.0.0.rst
docs/releases/v10.2.0.rst
docs/releases/v7.0.0.rst
docs/releases/v7.0.1.rst
docs/releases/v8.0.0.rst
docs/releases/v9.0.0.rst
docs/releases/v9.0.1.rst
postgrest.dict

* Moves Users and Groups into its own Database Authorization topic
* Moves JWT from Auth0 into Ecosystem
* Moves SQL User Management to a how-to
This is needed for documenting https://github.com/PostgREST/postgrest/pull/2742/.

Authentication as a reference

---

.readthedocs.yaml
docs/api.rst
docs/configuration.rst
docs/db_authz.rst
docs/errors.rst
docs/index.rst
docs/releases/v8.0.0.rst
docs/releases/v9.0.0.rst
docs/schema_cache.rst
docs/transactions.rst
requirements.txt

Added a transactions reference which simplifies the API page and explains other undocumented functionality.
Clarified schema cache and errors page using https://hemingwayapp.com/.
- Closes https://github.com/PostgREST/postgrest-docs/issues/511.
- Closes https://github.com/PostgREST/postgrest-docs/issues/384

Add Transactions reference

---

docs/references/api.rst

Changes in #620 and other PRs moved pages to another sections, so the links using `#hash-title` do not redirect well even though the pages are redirected in the RTD panel. 
This adds JavaScript redirects for most of those links.

Add JavaScript redirect from the old api.html to new pages and sections

---

docs/explanations/install.rst
docs/index.rst
docs/references/api/stored_procedures.rst
docs/references/auth.rst
docs/references/configuration.rst
postgrest.dict

- `app.settings` never worked with in-db. Correct this. (making it work seems unnecessary since it was meant to be used with env vars).
- `db-root-spec` added to the global table.

Fix in-db config settings

---

docs/references/configuration.rst

postgrest: FatalError {fatalErrorMessage = "Error in config ParseError \"postgrest.conf:14:22:\\n   |\\n14 | jwt-secret-is-base64=False\\n   |                      ^^^^^\\nunexpected \\\"False\\\"\\nexpecting \\\"false\\\", \\\"off\\\", \\\"on\\\", \\\"true\\\", '\\\"', '[', or digit\\n\""}

jwt-secret-is-base64 = False fails initialization, expects false

---

docs/references/api/resource_representation.rst

Resolves PostgREST/postgrest#2809
I hit this issue when replacing the backend for a client that was naively testing the `Content-Type` was `application/json`. This small change would have saved me significant debugging. Hopefully it will help others, too.

Note content-type for singular objects

---

docs/references/api/resource_embedding.rst

Hi, while reading the docs I noticed that example function `getallfilms` was marked as immutable. However, wouldn't stable be a more correct volatility marker given the fact that it queries the database and returns value of a database select?

Change example getallfilms to stable instead of immutable

---

.gitignore
docs/references/api/resource_representation.rst
shell.nix

This was missing on https://postgrest.org/en/stable/references/api/resource_representation.html

add request body handling

---

docs/references/api.rst
docs/references/api/domain_representations.rst
postgrest.dict

For https://github.com/PostgREST/postgrest/pull/2839
[Rendered doc](https://postgrest--655.org.readthedocs.build/en/655/references/api/domain_representations.html).

add domain representations

---

docs/integrations/systemd.rst

Add a regular account to reduce operational security risks, and set a failed retry 3 times.

Add a regular account to reduce operational security risks

---

default.nix
shell.nix

I have wrapped the commands: `build`, `linkcheck`, `dictcheck` and `spellcheck` into a single command `postgrest-docs-check`. It is easier to use this command to check everything before pushing.

dev: add postgrest-docs-check

---

docs/references/admin.rst
docs/references/api/tables_views.rst

Related to https://github.com/PostgREST/postgrest/pull/2985

Version not set when invalid URI or key/value format

---

docs/references/api/cors.rst
docs/references/configuration.rst
postgrest.dict

Add documentation for CORS config.

add documentation for server-cors-allowed-origins config

---

docs/references/auth.rst
docs/references/transactions.rst

Add documentation for statement timeout set on functions. Also move `impersonated role settings` from `auth.rst` to `transactions.rst`.

add documentation for statement_timeout set on functions

---

docs/references/configuration.rst

Introduces special value of `0` for port to be assigned randomly
Depends on https://github.com/PostgREST/postgrest/pull/3034

server-port can be 0

---

docs/conf.py
docs/explanations/install.rst
docs/shared/installation.rst
docs/tutorials/tut0.rst
postgrest.dict

Closes #702
- Used [the shared file approach to avoid duplicating code](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/reuse.html#include-a-shared-file),
- Also Modified all references of "OS X" to "macOS" (ref: https://en.wikipedia.org/wiki/MacOS#cite_note-10)

Add PostgREST installation using package managers to tut0

---

docs/how-tos/create-soap-endpoint.rst
docs/how-tos/providing-html-content-using-htmx.rst
docs/how-tos/providing-images-for-img.rst
docs/how-tos/working-with-postgresql-data-types.rst
docs/references/api.rst
docs/references/api/media_type_handlers.rst
docs/references/api/resource_representation.rst
docs/references/api/stored_procedures.rst
docs/references/configuration.rst
docs/references/errors.rst
docs/references/transactions.rst
postgrest.dict

For https://github.com/PostgREST/postgrest/pull/2825 and https://github.com/PostgREST/postgrest/pull/3076.
Drops `raw-media-types` and updates all previous how-tos relying on it.

reference: media type handlers

---

docs/references/api/pagination_count.rst

Mentions query parameters first.

Priorize query parameters instead of headers in limits and pagination

---

docs/references/api/media_type_handlers.rst

For https://github.com/PostgREST/postgrest/pull/3103

fix: correct any media type handler

---

docs/tutorials/tut1.rst

Fix secret command to avoid non-ascii alphanumerics

---

docs/references/transactions.rst

Spell correct "callounter" to "callcounter"

Spelling correction
